name = "koleksi-dr-pinguin"
main = "src/index.js"
compatibility_date = "2026-09-09"
compatibility_flags = ["nodejs_compat"]
account_id = "1ef0240f16747fd792f70e13c29790e0"

[assets]
directory = "."
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
run_worker_first = true

[observability]
enabled = true
head_sampling_rate = 0.1
