name = "koleksi-dr-pinguin-cf"
main = "src/index.js"
compatibility_date = "2026-09-09"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
run_worker_first = true
